### ISSUE TITLE
From Hapi.js to Elixir/Phoenix

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#104]
As mention in https://github.com/dwyl/labels/issues/94 we want to move the project to Elixir/Phoenix to make it easier to maintain and fix bugs.

The following branch already contains the initial work to create a new Phoenix application

- [x] Update gitignore to make sure to remove the `deps` folder.
- [x] I don't think this project will use any of the emails, dashboard, liveview, gettext or ecto features. We could create the new Phoenix application with the following flags: `mix phx.new labels --no-mailer --no-ecto --no-dashboard --no-live --no-gettext
  see:
![image](https://user-images.githubusercontent.com/6057298/155980960-6f8dd843-faad-42e6-932d-72d6c2560a3d.png)
However this step is not required and we might end up using at least the database later on: https://github.com/dwyl/labels/issues/94#issuecomment-1054201834

- [x] Once the Phoenix project is initialized we can deploy it to Fly.io and use continuous deployment to add features.
- [ ] ~Add Github authentication using the [Auth app](https://github.com/dwyl/auth):~
![image](https://user-images.githubusercontent.com/6057298/155981731-1b0fa5fa-af6a-46fb-822e-e5631e2bf4a6.png)
We want to make sure that only Github authentication is used as we need the Github token for API requests.

- [x] Use elixir-auth-github for authentication

**Comment by SimonLab** [comment]
I've also just noticed the Phoenix application has been created with the name `app`:
https://github.com/dwyl/labels/blob/430bc1691ee32f5d4b135d90d4cc05a8ac61bc1b/mix.exs#L6

We can make it more specific and rename (or recreate the project) with the name `labels`.

**Comment by SimonLab** [comment]
Trying to deploy the new Phoenix labels app on Fly.io by following https://fly.io/docs/getting-started/elixir/
`fly launch`:
![image](https://user-images.githubusercontent.com/6057298/156006378-cc3bc60f-91b4-4cca-9f68-85beeec1a9bc.png)

I'm not sure which organization to select (or if we need to create a new one), I'll need to read a bit more about Fly organization first

**Comment by SimonLab** [comment]
First "dummy" version deployed on Fly.io: https://labels.fly.dev/

- `flyctl launch`
- I've added the appication to the existing `Hits` organization. First I've created a new org "labels" however this ask for payment card and thought it would add more running cost
```bash
Would you like to setup a Postgresql database now? Yes
For pricing information visit: https://fly.io/docs/about/pricing/#postgresql-clusters
Select configuration: Development - Single node, 1x shared CPU, 256MB RAM, 1GB disk
```
@nelsonic feel free to remove the app or the postgres as I'm not sure if there will be more cost added by the labels app.

```bash
? Would you like to deploy now? Yes
Deploying labels
```
- `flyctl status`:   Hostname = labels.fly.dev 
- `flyctl open`:
![image](https://user-images.githubusercontent.com/6057298/156177081-ba576880-d426-4a03-8fdf-ed724a5dc188.png)

I'm now reading the continuous deployment documentation: https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

**Comment by SimonLab** [comment]
Continuous deployment done with the following commit: https://github.com/dwyl/labels/pull/105/commits/b6814dcc6404f6c47e352dc1fe47d8a23f2802c3
This create a "Fly Deploy" Github action which deploys the application on every push to the repository. We'll change this action to make sure to only deploy when a PR is merge to main similar to the Hits action: https://github.com/dwyl/hits/blob/main/.github/workflows/ci.yml

**Comment by SimonLab** [comment]
I'm adding elixir-auth-github as we only want Github for authentication and we can manage the scope to use when using the user token with the Github API to create the labels (see https://github.com/dwyl/labels/issues/104#issuecomment-1054378450)

I'm currently creating an authentication module Plug to manage login/logout, see https://hexdocs.pm/phoenix/plug.html#module-plugs

**Comment by SimonLab** [comment]
The Phoenix application is now deployed at https://labels.fly.dev/
